---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow will install a variety of Python versions and other
# dependencies to run tests. For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python testing

on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*
  # Run once per week (Monday at 04:00 UTC)
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
        skip-is-error:
          - true
        override-pyproject-python:
          - ''
        include:
          - python-version: 3.7
            override-pyproject-python: 3.6.1  # i.e. keep the existing number
            skip-is-error: false
          - python-version: 3.8
            skip-is-error: false
          - python-version: 3.9
            skip-is-error: false

    steps:
      - name: Check out antsibull-docs
        uses: actions/checkout@v3
        with:
          path: antsibull-docs

      - name: Check out dependent project antsibull-core
        uses: actions/checkout@v3
        with:
          repository: ansible-community/antsibull-core
          path: antsibull-core
          ref: >-
            ${{ contains(fromJson('["3.6", "3.7", "3.8"]'), matrix.python-version) && 'stable-1' || 'main' }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          if [ "${{ matrix.python-version }}" != "3.6" ]; then
            # ^3.6 collides with 3.6.1 lower bound in antsibull-core
            sed -i -e 's/^python = .*/python = "^${{ matrix.override-pyproject-python || matrix.python-version }}"/' pyproject.toml
          fi
          poetry install
          poetry update
        working-directory: antsibull-docs

      - name: Test with pytest and upload coverage stats
        run: |
          ./test-pytest.sh ${{ matrix.skip-is-error && '--error-for-skips' || '' }}
          poetry run coverage xml -i
          poetry run codecov
        working-directory: antsibull-docs

  # Poetry won't install dependencies for antsibull-docs anymore on 3.6. So let's do this differently.
  build-3-6:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.6

    steps:
      - name: Check out antsibull-docs
        uses: actions/checkout@v3
        with:
          path: antsibull-docs

      - name: Check out dependent project antsibull-core
        uses: actions/checkout@v3
        with:
          repository: ansible-community/antsibull-core
          path: antsibull-core
          ref: stable-1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -e . -e ../antsibull-core \
                      asynctest cryptography pytest "pytest-asyncio>=0.12"
        working-directory: antsibull-docs

      - name: Test with pytest
        run: >-
          python -W 'ignore:"@coroutine" decorator is deprecated::asynctest.case' -m pytest -vv tests
        working-directory: antsibull-docs
