---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# This workflow will install Python 3.10 and other dependencies to lint the code.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python linting

on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
    branches:
      - main
      - stable-*
  # Run once per week (Monday at 04:00 UTC)
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # frozenlist 1.2.0 doesn't like Python 3.11; bump this once we drop support for older Python versions
          - '3.10'

    steps:
      - name: Check out antsibull-docs
        uses: actions/checkout@v3
        with:
          path: antsibull-docs

      - name: Check out dependent project antsibull-core
        uses: actions/checkout@v3
        with:
          repository: ansible-community/antsibull-core
          path: antsibull-core
          # TODO: As long as we still support Python 3.6, 3.7, and 3.8, use stable-1 instead of main!
          ref: stable-1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install
          poetry update
        working-directory: antsibull-docs

      - name: Lint with flake8
        run: |
          ./lint-flake8.sh
        working-directory: antsibull-docs

      - name: Lint with pyre
        run: |
          ./lint-pyre.sh
        working-directory: antsibull-docs
        if: always()

      - name: Lint with pylint
        run: |
          ./lint-pylint.sh
        working-directory: antsibull-docs
        if: always()

      - name: Lint with mypy
        run: |
          ./lint-mypy.sh
        working-directory: antsibull-docs
        if: always()
